use strum_macros::EnumString;

use std::collections::HashMap;

#[derive(Debug, EnumString, PartialEq, Eq, Hash, Copy, Clone)]
pub enum CityCard2 {
    algiers,
    atlanta,
    baghdad,
    bangkok,
    beijing,
    bogota,
    buenos aires,
    cairo,
    chennai,
    chicago,
    delhi,
    essen,
    ho chi minh,
    hong kong,
    istanbul,
    jakarta,
    johannesburg,
    karachi,
    khartoum,
    kinshasa,
    kolkata,
    lagos,
    lima,
    london,
    los angeles,
    madrid,
    manila,
    mexico city,
    miami,
    milan,
    montreal,
    moscow,
    mumbai,
    new york,
    osaka,
    paris,
    riyadh,
    san francisco,
    santiago,
    sao paulo,
    seoul,
    shanghai,
    st petersburg,
    sydney,
    taipei,
    tehran,
    tokyo,
    washington,
}
