use strum_macros::EnumString;

use std::collections::HashMap;

#[derive(Debug, EnumString, PartialEq, Eq, Hash, Copy, Clone)]
pub enum CityCard {
    Test
}

#[derive(Debug, EnumString, PartialEq, Eq, Hash, Copy, Clone)]
pub enum CityCard {
    Atlanta,
    Chicago,
    Washington,
    Miami,
    Montreal,
    SanFrancisco,
    LosAngeles,
    NewYork,
    London,
    Madrid,
    Paris,
    Essen,
    Algiers,
    MexicoCity,
    Milan,
    StPetersburg,
    Istanbul,
    Cairo,
    Moscow,
    Baghdad,
    Riyadh,
    Tehran,
    Karachi,
    Delhi,
    Mumbai,
    Kolkata,
    HongKong,
    Taipei,
    Shanghai,
    Beijing,
    Seoul,
    Tokyo,
    Osaka,
    Bangkok,
    Manila,
    HoChiMinh,
    Jakarta,
    Sydney,
    Chennai,
    Khartoum,
    Johannesburg,
    Kinshasa,
    Lagos,
    SaoPaulo,
    BuenosAires,
    Lima,
    Santiago,
    Bogota,
}

pub fn city_graph() -> HashMap<CityCard, Vec<CityCard>> {
    HashMap::from([
        (CityCard::Atlanta, vec![CityCard::Chicago, CityCard::Washington, CityCard::Miami]),
        (CityCard::Chicago, vec![CityCard::Montreal, CityCard::Atlanta, CityCard::SanFrancisco, CityCard::LosAngeles, CityCard::MexicoCity]),
        (CityCard::Washington, vec![CityCard::Atlanta, CityCard::Montreal, CityCard::NewYork]),
        (CityCard::Miami, vec![CityCard::Atlanta, CityCard::Washington, CityCard::MexicoCity, CityCard::Bogota]),
        (CityCard::Montreal, vec![CityCard::Chicago, CityCard::Washington, CityCard::NewYork]),
        (CityCard::SanFrancisco, vec![CityCard::Chicago, CityCard::LosAngeles, CityCard::Tokyo, CityCard::Manila]),
        (CityCard::LosAngeles, vec![CityCard::SanFrancisco, CityCard::Chicago, CityCard::MexicoCity, CityCard::Sydney]),
        (CityCard::NewYork, vec![CityCard::Washington, CityCard::Montreal, CityCard::London, CityCard::Madrid]),
        (CityCard::London, vec![CityCard::NewYork, CityCard::Madrid, CityCard::Paris, CityCard::Essen]),
        (CityCard::Madrid, vec![CityCard::NewYork, CityCard::London, CityCard::Paris, CityCard::SaoPaulo]),
        (CityCard::Paris, vec![CityCard::Madrid, CityCard::London, CityCard::Essen, CityCard::Algiers, CityCard::Milan]),
        (CityCard::Essen, vec![CityCard::London, CityCard::Paris, CityCard::StPetersburg, CityCard::Milan]),
        (CityCard::Algiers, vec![CityCard::Madrid, CityCard::Paris, CityCard::Istanbul, CityCard::Cairo]),
        (CityCard::MexicoCity, vec![CityCard::LosAngeles, CityCard::Chicago, CityCard::Miami, CityCard::Bogota, CityCard::Lima]),
        (CityCard::Milan, vec![CityCard::Istanbul, CityCard::Paris, CityCard::Essen]),
        (CityCard::StPetersburg, vec![CityCard::Essen, CityCard::Istanbul, CityCard::Moscow]),
        (CityCard::Istanbul, vec![CityCard::Milan, CityCard::Baghdad, CityCard::Cairo, CityCard::Algiers]),
        (CityCard::Cairo, vec![CityCard::Algiers, CityCard::Istanbul, CityCard::Baghdad, CityCard::Riyadh, CityCard::Khartoum]),
        (CityCard::Moscow, vec![CityCard::Istanbul, CityCard::StPetersburg, CityCard::Tehran]),
        (CityCard::Baghdad, vec![CityCard::Tehran, CityCard::Istanbul, CityCard::Cairo, CityCard::Karachi, CityCard::Riyadh]),
        (CityCard::Riyadh, vec![CityCard::Cairo, CityCard::Baghdad, CityCard::Karachi]),
        (CityCard::Tehran, vec![CityCard::Baghdad, CityCard::Delhi, CityCard::Karachi]),
        (CityCard::Karachi, vec![CityCard::Tehran, CityCard::Delhi, CityCard::Baghdad, CityCard::Riyadh, CityCard::Mumbai]),
        (CityCard::Delhi, vec![CityCard::Mumbai, CityCard::Tehran, CityCard::Karachi, CityCard::Kolkata, CityCard::Chennai]),
        (CityCard::Mumbai, vec![CityCard::Karachi, CityCard::Delhi, CityCard::Chennai]),
        (CityCard::Kolkata, vec![CityCard::Delhi, CityCard::Chennai, CityCard::Bangkok, CityCard::HongKong]),
        (CityCard::HongKong, vec![CityCard::Kolkata, CityCard::Bangkok, CityCard::Shanghai, CityCard::Taipei, CityCard::HoChiMinh, CityCard::Manila]),
        (CityCard::Taipei, vec![CityCard::HongKong, CityCard::Manila, CityCard::Shanghai, CityCard::Osaka]),
        (CityCard::Shanghai, vec![CityCard::Beijing, CityCard::HongKong, CityCard::Taipei, CityCard::Tokyo, CityCard::Seoul]),
        (CityCard::Beijing, vec![CityCard::Shanghai, CityCard::Seoul]),
        (CityCard::Seoul, vec![CityCard::Beijing, CityCard::Shanghai, CityCard::Tokyo]),
        (CityCard::Tokyo, vec![CityCard::Seoul, CityCard::Shanghai, CityCard::Osaka, CityCard::SanFrancisco]),
        (CityCard::Osaka, vec![CityCard::Tokyo, CityCard::Taipei]),
        (CityCard::Bangkok, vec![CityCard::Chennai, CityCard::Jakarta, CityCard::HoChiMinh, CityCard::HongKong, CityCard::Kolkata]),
        (CityCard::Manila, vec![CityCard::SanFrancisco, CityCard::Taipei, CityCard::HoChiMinh, CityCard::HongKong, CityCard::Sydney]),
        (CityCard::HoChiMinh, vec![CityCard::Manila, CityCard::Bangkok, CityCard::Jakarta, CityCard::HongKong]),
        (CityCard::Jakarta, vec![CityCard::HoChiMinh, CityCard::Bangkok, CityCard::Chennai, CityCard::Sydney]),
        (CityCard::Sydney, vec![CityCard::Jakarta, CityCard::Manila, CityCard::LosAngeles]),
        (CityCard::Chennai, vec![CityCard::Jakarta, CityCard::Bangkok, CityCard::Mumbai, CityCard::Delhi, CityCard::Kolkata]),
        (CityCard::Khartoum, vec![CityCard::Cairo, CityCard::Lagos, CityCard::Kinshasa, CityCard::Johannesburg]),
        (CityCard::Johannesburg, vec![CityCard::Khartoum, CityCard::Kinshasa]),
        (CityCard::Kinshasa, vec![CityCard::Khartoum, CityCard::Johannesburg, CityCard::Lagos]),
        (CityCard::Lagos, vec![CityCard::Khartoum, CityCard::Kinshasa, CityCard::SaoPaulo]),
        (CityCard::SaoPaulo, vec![CityCard::Madrid, CityCard::Lagos, CityCard::Bogota, CityCard::BuenosAires]),
        (CityCard::BuenosAires, vec![CityCard::SaoPaulo, CityCard::Bogota]),
        (CityCard::Lima, vec![CityCard::Santiago, CityCard::Bogota, CityCard::MexicoCity]),
        (CityCard::Santiago, vec![CityCard::Lima]),
        (CityCard::Bogota, vec![CityCard::Lima, CityCard::BuenosAires, CityCard::SaoPaulo, CityCard::MexicoCity, CityCard::Miami]),
    ])
}
